Create witch custom id
parse-community/Parse-Swift pull request #225
Opened 2021-09-06 10:22 UTC by lsmilek1

Added createWithCustomObjectId parameter in .save() functions to remove the need of setting isIgnoreCustomObjectIdConfig = true and allowCustomObjectId = true for a mixed custom objectId environment

2021-09-06 10:25 UTC, lsmilek1 commented
As this is my first time I encountered XCTests and also started updating other branch and per your [comment](https://github.com/parse-community/Parse-Swift/issues/220#issuecomment-911668908) added new branch later, I am really not sure If I got the things right. I apologise in advance!

2021-09-06 14:13 UTC, cbaker6 commented
Can you resolve the conflicts?

2021-09-06 14:14 UTC, cbaker6 commented
Also, it looks like you started from the branch I created as opposed to branching from the main

2021-09-06 15:42 UTC, lsmilek1 commented
Sure, I will have a look on the conflicts. I am sorry, I was never using git control before. I started from non-main branch, you are right (not knowing there will be such conflicts) and after you mentioned it I had actually all the code modified, so I then tried to merge it in the forked main and then create PR... Obviously that is not the way to do that.

2021-09-06 15:50 UTC, cbaker6 commented
> Also, I did not know how to run the XCTests, as I never did any before and I do not have local Parse Server running (do I need that?) so if you could give me a hint that would be great!

You don't need a parse server to run the tests. You can run them locally using Xcode, https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/05-running_tests.html or they will run automatically in the CI when you fix the conflicts.

2021-09-06 15:54 UTC, cbaker6 requested changes

2021-09-06 15:54 UTC, cbaker6 commented on CHANGELOG.md
> +- Added createWithCustomObjectId parameter in .save() functions to remove the need of setting isIgnoreCustomObjectIdConfig = true and allowCustomObjectId = true for a mixed custom objectId environmen
Be sure to follow the format of the rest of the change log, you are missing the PR link and contributor information

2021-09-06 16:20 UTC, cbaker6 requested changes

2021-09-06 16:20 UTC, cbaker6 commented on CHANGELOG.md
> +__Improvements__
This is in the wrong place. It should be above 1.9.8 as that version is already released

2021-09-06 18:04 UTC, cbaker6 commented
You need to install SwiftLint and ensure you fix all of the errors and warnings before committing or else your builds won't pass. If SwiftLint is installed, you will see the build errors and warnings on your local computer https://github.com/parse-community/Parse-Swift/blob/main/CONTRIBUTING.md

2021-09-07 08:08 UTC, lsmilek1 commented
I believe this is at the end way over my competence. I already see I am breaking it more than contributing, especially the tests, and in the Swift playgrounds I will have to spin up a local version of the server as I understood your comment. This is all new to me and even I somehow make the tests to pass, the test logic will be rather wrong. 

The goal was to remove the need of `allowCustomObjectId` and `isIgnoreCustomObjectIdConfig` and invert the logic into one optional flag `createWithCustomId` to reduce the code length on each .save() as basically only few objects would make use of the `allowCustomObjectId` + `isIgnoreCustomObjectIdConfig`. I believe a wrapper `.save()` in the non-SDK classes will be more reasonable way to do that instead of attempting to change SDK's essential behavior.

2021-09-07 08:08 UTC, closed without merging

2021-09-07 11:01 UTC, cbaker6 commented
> I already see I am breaking it more than contributing, especially the tests,

the tests are there to ensure core logic isn’t broken when changes are made. The changes you were making will definitely break core logic, and some of the tests that fail will need to be changed. It also allows us to see what breaks and if the change should be added.

I don’t see a commit where you fixed the linking so we can at least see the test failures to evaluate your changes.

> and in the Swift playgrounds I will have to spin up a local version of the server as I understood your comment.

this is as simple as downloading docker, forking a repo and running a one liner (see my comment below from the readme). If back4app allows you to spin up a free instance you can use that or any other service and tear it down when you are finished.

> This is all new to me and even I somehow make the tests to pass, the test logic will be rather wrong.

I think it’s useful to think about and develop tests for added features and see how/why a change breaks current tests. It will also allow you to learn more about how the SDK is designed and then help you discover bugs in the future