WIP: Strip out unchanged keys on object update
parse-community/Parse-Swift pull request #263
Opened 2021-10-21 15:05 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Issue Description

Draft PR for ideas / suggestions for improvements around this approach.

If this isn't suitable for this project, I'll be happy to work on this branch for my own usage. I would welcome feedback so I can make sure my fork is as good as it can be 😊 

Related issue: #242

### Approach

Stores objects in JSON form in memory. When objects are saved, adds unchanged keys to SkipKeys.

### TODOs before merging

- [ ] Add tests
- [ ] Add entry to changelog

2021-11-04 15:40 UTC, cbaker6 requested changes

2021-11-04 15:40 UTC, cbaker6 commented on Sources/ParseSwift/Storage/JSONStorage.swift
> +                (json[keyName] as? NSObject) == (previousStore[keyName] as? NSObject)
Will need to remove casting to `NSObject` as it doesn't work well with this SDK. See #274 and #275 for workarounds.

2022-09-03 18:05 UTC, mtrezza commented
Re-opened as this PR suggests a improvements tracked in https://github.com/parse-community/Parse-Swift/issues/401

2022-09-11 14:37 UTC, cbaker6 commented
Closing due to inactivity since 10/21. @dblythy feel free to reopen if you can address the issues mentioned in https://github.com/parse-community/Parse-Swift/pull/263#issuecomment-954269490, https://github.com/parse-community/Parse-Swift/pull/263#issuecomment-954306992, and https://github.com/parse-community/Parse-Swift/pull/263#discussion_r742961428 and if you think the contribution of this PR will be an improvement over #406

2022-09-11 14:37 UTC, closed without merging

2022-09-11 21:06 UTC, mtrezza commented
Since you closed this, we'll need to open another issue to track this discussion about further improvement.

2022-09-12 05:03 UTC, dblythy commented
Yes - sorry - I closed this as hearing the valid comments from @Vortec4800, I decided this approach probably wasn't the best way to go. I might reconsider / retry having a crack again in the future