feat: add discardableResult to certain functions
parse-community/Parse-Swift pull request #385
Opened 2022-07-16 11:23 UTC by vdkdamian

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Issue Description
If you want to execute save() or fetch(),... the function returns the ParseObject. If you don't need it you need to cancel it out with an underscore replacement.

Related issue: #384

### Approach
`@discardableResult` adds the possibility to skip the result as developer.
It's up to the developer to decide whether they use the result or not.

### TODOs before merging

- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2022-07-17 21:29 UTC, vdkdamian commented
@cbaker6 Could you help me point why the tests are failing? 
I tried running the tests on my mac, but I am on the Ventura Beta. The tests are failing on something I noticed since the beginning of the Beta's. All function like "saveAll", "fetchAll",... give me a warning. Might be a future problem when Ventura and iOS 16 release. 

But I don't think that has anything to do with the little changes I made
<img width="1484" alt="Scherm­afbeelding 2022-07-17 om 23 23 27" src="https://user-images.githubusercontent.com/44820440/179425450-8b36ee2c-78cf-4440-8946-8dae0e9ea19b.png">

2022-07-18 01:58 UTC, cbaker6 commented
I wouldn’t worry about the failing tests on your system if they aren’t showing up in the CI. What does show in the CI looks like you didn’t lint the project after your changes. You will need to fix linting before this can be merged.

2022-07-19 00:29 UTC, cbaker6 commented
> I'm testing this line: ParseLiveQueryTests.testEventCreateSubscriptionCallback() and it was successful. I don't get why it fails here. Any ideas?

This is a random failure that only occurs in the CI so you can ignore.

Can you add `@discardableResult` to `ParseInstallation` and `ParseUser`?

2022-07-19 00:37 UTC, cbaker6 requested changes

2022-07-19 00:37 UTC, cbaker6 commented on CHANGELOG.md
> +- Added @discardableResult to allow developers to choose whether or not certain functions should return a result ([#385](https://github.com/parse-community/Parse-Swift/pull/385)), thanks to [Damian V
You can remove the `@` here. If someone's GitHub name is `@discardableResult` you will be linking them to the changelog

2022-07-19 11:22 UTC, vdkdamian commented
Now something is wrong with linux?

2022-07-19 14:40 UTC, cbaker6 approved these changes
LGTM

2022-07-19 14:40 UTC, merged