Add cloud function/job calls and user password reset.
parse-community/Parse-Swift pull request #43
Opened 2020-12-29 21:21 UTC by cbaker6

- Also adds more command tests for User and cleans up user docs

2020-12-30 02:24 UTC, cbaker6 commented
@TomWFox can you review the docs?

@pranjalsatija can you review?

2020-12-31 13:21 UTC, TomWFox requested changes
Just a few minor changes... otherwise LGTM

2020-12-31 13:21 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     associated with the user account. This email allows the user to securely reset their password on the Parse site.
Same as my other comment.

2020-12-31 13:21 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     associated with the user account. This email allows the user to securely reset their password on the Parse site.
and here.

2020-12-31 13:21 UTC, TomWFox commented on Sources/ParseSwift/Types/ParseFile.swift
> +     The link to the file online that should be fetched before uploading to the parse server.
```suggestion
     The link to the file online that should be fetched before uploading to the Parse Server.
```

2020-12-31 13:21 UTC, TomWFox commented on Sources/ParseSwift/Types/ParseFile.swift
> +     [S3 adapter](https://github.com/parse-community/parse-server-s3-adapter#adding-metadata-and-tags)
```suggestion
     - parameter tags: Optional key value pairs to be stored with file object.
     - note: `metadata` and `tags` is file adapter specific and not supported by all file adapters.
     For more, see details on the
     [S3 adapter](https://github.com/parse-community/parse-server-s3-adapter#adding-metadata-and-tags).
```

2020-12-31 13:21 UTC, TomWFox commented on Sources/ParseSwift/Types/ParseFile.swift
> +     [S3 adapter](https://github.com/parse-community/parse-server-s3-adapter#adding-metadata-and-tags)
```suggestion
     - parameter metadata: Optional key value pairs to be stored with file object.
     - parameter tags: Optional key value pairs to be stored with file object.
     - note: `metadata` and `tags` is file adapter specific and not supported by all file adapters.
     For more, see details on the
     [S3 adapter](https://github.com/parse-community/parse-server-s3-adapter#adding-metadata-and-tags).
```

2020-12-31 14:49 UTC, cbaker6 commented
@TomWFox can you add `spm-test-5_2` to the branch protections? This ensures we are still Swift backwards compatible, which I've managed to fix/break in the last couple of PRs. The issue is Swift 5.3 reduced the need for `self.` inside of closures, so the compiler for 5.3 doesn't complain when you don't use it. Older versions of Swift require the use of `self` inside of closures.

2020-12-31 14:56 UTC, TomWFox approved these changes

2021-01-02 19:16 UTC, cbaker6 commented
@TomWFox can look at the documentation I added for the `batchLimit` argument of `saveAll/deleteAll` in `ParseObject.swift`, `ParseUser.swift`, `ParseInstallation.swift`? There are two of these in each file.

2021-01-03 20:43 UTC, TomWFox requested changes

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseObject.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
I think this is slightly better...
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseObject.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseObject.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseObject.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseUser.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseInstallation.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseInstallation.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseInstallation.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:43 UTC, TomWFox commented on Sources/ParseSwift/Objects/ParseInstallation.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
```suggestion
     - parameter batchLimit: The maximum number of objects to send in each batch. If the items to be batched
```

2021-01-03 20:45 UTC, cbaker6 commented on Sources/ParseSwift/Objects/ParseObject.swift
> +     - parameter batchLimit: The amount of objects to send in each batch. If the items to be batched
Agreed

2021-01-03 21:19 UTC, TomWFox approved these changes

2021-01-04 03:34 UTC, merged