LiveQuery Support
parse-community/Parse-Swift pull request #45
Opened 2021-01-04 02:51 UTC by cbaker6

Minimum requirements: macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0

2021-01-08 04:26 UTC, cbaker6 commented
@TomWFox can you review the docs? This PR is moving into testing.

2021-01-08 04:37 UTC, cbaker6 commented
@pmmlo Can you test this locally?

I have a [server setup](https://github.com/netreconlab/parse-hipaa/tree/parse-swift) via docker that will work out-of-the box with the Playgrounds files if you need it. It also gives you dashboard so you can add/remove/edit fields in there.

The Playgrounds file with how to use LiveQuery is here: https://github.com/parse-community/Parse-Swift/blob/988b0d141df1453fc1c01dc268e49f8f3b2af7bc/ParseSwift.playground/Pages/11%20-%20LiveQuery.xcplaygroundpage/Contents.swift#L33-L88

From what I've seen Subscribe and all of the Events seem to work fine.

I broke something in unsubscribe and update, but it's probably an easy fix I'l get to later.

2021-01-08 06:13 UTC, pmmlo commented
> @pmmlo Can you test this locally?

Smooth as butter.  Just changed update query and unsubscribe at the bottom to try-catch but doesn't matter.  Gist here if you care: [https://gist.github.com/pmmlo/a40957e1f51ffaacf47c511cc2a9e034](url)

Add, update, and delete were instantly broadcasted.

Thanks @cbaker6 !

2021-01-08 16:17 UTC, cbaker6 commented
@pmmlo great to hear! I fixed unsubscribe recently.

2021-01-08 20:27 UTC, pmmlo commented
> What do you think about the process of using LiveQuery and subscribing/unsubscribing? I'm hoping it feel more natural...

I'm not the best person to ask, but I think it handles A LOT for the devs and was very easy to use with the Playground.  I personally like it, and it makes sense to me.

Worked very well during my local testing.  It feels more natural than the QueryConstraints framework, but I even learned to like that.  I'll let you know if I get struck by inspiration on improving this while I use it 😏

2021-01-10 06:16 UTC, cbaker6 commented
@pranjalsatija can you review?

2021-01-10 19:23 UTC, TomWFox requested changes
Only being picky really...

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
> +     - parameter serverURL: The URL of the Parse Live Query Server to connect to.
```suggestion
     - parameter serverURL: The URL of the `ParseLiveQuery` Server to connect to.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
> +    /// Manually establish a connection to the `ParseLiveQuery` server.
```suggestion
    /// Manually establish a connection to the `ParseLiveQuery` Server.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift
> +    /// Manually disconnect from the `ParseLiveQuery` server.
```suggestion
    /// Manually disconnect from the `ParseLiveQuery` Server.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/Protocols/ParseLiveQueryDelegate.swift
> +     Respond to authentication requests from a ParseLiveQuery server. If you become a delegate
```suggestion
     Respond to authentication requests from a ParseLiveQuery Server. If you become a delegate
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/Protocols/SubscriptionHandlable.swift
> +     Tells the handler that an event has been received from the `ParseLiveQuery` server.
```suggestion
     Tells the handler that an event has been received from the `ParseLiveQuery` Server.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/Subscription.swift
> + Represents an update on a specific object from the `ParseLiveQuery` server.
```suggestion
 Represents an update on a specific object from the `ParseLiveQuery` Server.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/LiveQuery/Subscription.swift
> +     - returns: The same subscription, for easy chaining
```suggestion
     - parameter eventType: The event type to handle. You should pass one of the enum cases in `Event`.
     - parameter handler: The callback to register.
     - returns: The same subscription, for easy chaining.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/Storage/PrimitiveObjectStore.swift
> +    /// - parameter key: The unique key value of the object
```suggestion
    /// - parameter key: The unique key value of the object.
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/Types/Query.swift
> +     If you are only interested in the change of the name field, you can set query.fields to "name".
```suggestion
     If you are only interested in the change of the name field, you can set `query.fields` to "name".
```

2021-01-10 19:23 UTC, TomWFox commented on Sources/ParseSwift/Types/Query.swift
> +     If you are only interested in the change of the name field, you can set query.fields to "name".
```suggestion
     If you are only interested in the change of the name field, you can set `query.fields` to "name".
```

2021-01-10 20:17 UTC, merged

2021-01-16 00:19 UTC, pmmlo commented
@cbaker6 I had a little time to test this with a HTTPS server and `.subscribe` and `.handleSubscribe` return expected callbacks.  However, after about ~29s (timed twice, but seems consistent), I get these two errors:
```
2021-01-15 16:12:45.010269-0800 Member[60224:14126091] [tcp] tcp_input [C1.1:3] flags=[R] seq=3454113186, ack=0, win=0 state=LAST_ACK rcv_nxt=3454113186, snd_una=1642147939
2021-01-15 16:12:45.011230-0800 Member[60224:14126091] [tcp] tcp_input [C1.1:3] flags=[R] seq=3454113186, ack=0, win=0 state=CLOSED rcv_nxt=3454113186, snd_una=1642147939
2021-01-15 16:12:45.012326-0800 Member[60224:14126091] [tcp] tcp_input [C1.1:3] flags=[R] seq=3454113186, ack=0, win=0 state=CLOSED rcv_nxt=3454113186, snd_una=1642147939
```

It seems like the Subscription is timing out or crashing.  I have guesses on what may be going on but thought you may know immediately.

Here's the code:

```
query = Team.query("member" == User.current?.objectId)
guard let subscription = query.limit(1).subscribe else { return }

subscription.handleSubscribe { subscribedQuery, isNew in
    if isNew {
        print("Successfully subscribed to new query \(subscribedQuery)")
    } else {
        print("Successfully updated subscription to new query \(subscribedQuery)")
    }
}

subscription.handleEvent { _, event in
    print("\(event)")
    switch event {
    case .entered(let object):
        print("Entered: \(object)")
    case .left(let object):
        print("Left: \(object)")
    case .created(let object):
        print("Created: \(object)")
    case .updated(let object):
        print("Updated: \(object)")
    case .deleted(let object):
        print("Deleted: \(object)")
    }
}

 subscription.handleUnsubscribe { query in
    print("Unsubscribed from \(query)")
}
```

I never receive any events, despite editing in dashboard.  I can unsubscribe with the expected response before the two errors fire.

Any ideas?

2021-01-16 00:25 UTC, cbaker6 commented
Did you register your `Team` class for LiveQuery in your index file of your Parse Server?

```
liveQuery: {
    classNames: ["GameScore", "Book", "Author"] // List of classes to support for query subscriptions
  },
```

I tested this LiveQuery by leaving a subscriptions on over night in the simulator for an iPhone and Apple Watch and it didn't disconnect and sent events the next day.

2021-01-16 00:27 UTC, cbaker6 commented
You can see how I setup the server for playgrounds here: https://github.com/netreconlab/parse-hipaa/blob/parse-swift/parse/index.js

2021-01-16 00:30 UTC, pmmlo commented
> You can see how I setup the server for playgrounds here: https://github.com/netreconlab/parse-hipaa/blob/parse-swift/parse/index.js

I have something similar with Express as well.  I also ensured livequery server was initialized and the `Team` class name was listed.

I guess not as straight forward as I thought it would be.  I will dig into this then.  Must be an implementation issue.

2021-01-16 00:31 UTC, pmmlo commented
> Also, for your server, are you behind a proxy? If you are using Nginx be sure to setup https://www.nginx.com/blog/websocket-nginx/

I'm actually running it in a k8s cluster with an ingress.

2021-01-16 00:34 UTC, cbaker6 commented
But your http works when you use playgrounds and docker?

2021-01-16 00:34 UTC, pmmlo commented
Yup, even graphql.

2021-01-16 00:36 UTC, pmmlo commented
I ran playgrounds using your docker and playgrounds.  Worked well there.

2021-01-16 00:37 UTC, cbaker6 commented
Maybe it's configuration, can you check if https://github.com/parse-community/Parse-Swift/blob/84f923141b0994dc50bb924cc8fbcb6fad228158/Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift#L192

is converting your url to `wss` since you are tls?

2021-01-16 00:38 UTC, pmmlo commented
> Maybe it's configuration, can you check if
> 
> https://github.com/parse-community/Parse-Swift/blob/84f923141b0994dc50bb924cc8fbcb6fad228158/Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift#L192
> 
> is converting your url to `wss` since you are tls?

This looks promising.  I think it may be...let me try to test this.

2021-01-16 00:50 UTC, pmmlo commented
It's wss.

2021-01-16 01:27 UTC, cbaker6 commented
Are you able to connect using a site like https://www.websocket.org/echo.html

2021-01-16 01:47 UTC, pmmlo commented
There was an undocumented backend timeout of 30 seconds in AWS that seems to have been the issue.  Would have guessed 30 seconds was enough...  Just raised it to 5 minutes, which should be more than enough.  No error, but I'm still not getting anything from .handleEvent(). I'll play around with this and post, if I figure out my issue. ;)

2021-01-16 01:52 UTC, pmmlo commented
Just started working after I put in breakpoints.  Changed nothing, and I have an empty console.  Maybe I should have cleaned the project first...

Sorry!