Add Roles and Relations
parse-community/Parse-Swift pull request #54
Opened 2021-01-17 18:34 UTC by cbaker6

2021-01-20 18:58 UTC, cbaker6 commented
@TomWFox can you look over the docs?

I'm working on the rest of the tests for Role and Relation, but I believe I have most if not all the docs in

2021-01-21 17:12 UTC, TomWFox requested changes
Only minor requests...

2021-01-21 17:12 UTC, TomWFox commented on Sources/ParseSwift/Types/Query.swift
> +     Exclude specific keys for a`ParseObject`s. Default is to nil.
```suggestion
     Exclude specific keys for a `ParseObject`. Default is to nil.
```

2021-01-21 17:12 UTC, TomWFox commented on Sources/ParseSwift/Types/ParseRelation.swift
> +        - returns: A relation query
```suggestion
        - returns: A relation query.
```

2021-01-21 17:12 UTC, TomWFox commented on Sources/ParseSwift/Operations/ParseOperation.swift
> + indirectly created from any `ParseObject` by using its' `operation` property.
```suggestion
 indirectly created from any `ParseObject` by using its `operation` property.
```

2021-01-21 17:25 UTC, cbaker6 commented
Thanks @TomWFox! I recently added some of the missing query constraints. Not too many, but can look at them? https://github.com/parse-community/Parse-Swift/pull/54/commits/6bb02bb2f746b4f5164c323812a49553eec0b4e6

2021-01-21 18:03 UTC, TomWFox requested changes

2021-01-21 18:03 UTC, TomWFox commented on Sources/ParseSwift/Types/Query.swift
> + Add a constraint to the query that requires a particular key's time is related a specified time. E.g. "3 days ago".
```suggestion
 Add a constraint to the query that requires a particular key's time is related to a specified time. E.g. "3 days ago".
```

2021-01-21 18:21 UTC, merged